---
# tasks file for kubernetes
- name: Including variables.yml
  include_vars:
    file: variables.yml

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Adding the apt signing key for kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - Update apt packages

- name: Installing apt-transport-https
  apt:
    name: apt-transport-https
  tags:
    - Installing dependencies

- name: Adding repository for kubernetes
  become: true
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    filename: kubernetes
  tags:
    - Update apt packages 

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Installing apt-transport-https
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl']
  tags:
    - Installing dependencies

- name: Booting up service
  systemd:
    name: kubelet
    state: started
    enabled: true

- name: Kubeadm reset and init
  become: true
  shell: kubeadm reset -f; kubeadm init --apiserver-advertise-address="192.168.11.11" --pod-network-cidr 10.1.0.0/16
  register: kubeadmout

- name: kubeadm output
  debug:
    var: kubeadmout.stdout

#- name: Kubeadm reset and init                                                                                           
#  become: true                                                                                                           
#  shell: kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
#  register: kubeadmapply                                                                                                   
                                                                                                                         
#- name: kubeadm output                                                                                                   
#  debug:                                                                                                                 
#    var: kubeadmapply.stdout 

- name: making directory for kubernetes
  file:
    path: /home/vagrant/.kube
    state: directory

- name: Copying config file
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/vagrant/.kube/config"
    remote_src: yes

- name: Kubeadm reset and init                                                                                           
  become: true                                                                                                           
  shell: kubectl apply -f https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml  
  register: kubeadmapply  

- name: kubeadm output                                                                                                   
  debug:                                                                                                                 
    var: kubeadmapply.stdout 

#- name: Kubeadm reset and init                                                                                           
#  become: true                                                                                                           
#  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"  
#  register: kubeadmapply2                                                                                                
 
#- name: kubeadm output
#  debug:                                                                                                                 
#    var: kubeadmapply2.stdout

 
