---
# tasks file for docker

- name: Including Variables.yml
  include_vars:
    file: variables.yml

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Installing dependencies
  become: true
  apt:
    name: ['apt-transport-https','ca-certificates','curl','gnupg-agent', 'software-properties-common']
  tags:
    - installing dependencies

- name: Adding the apt signing key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88
  tags:
    - Update apt packages

- name: Adding repository for Java
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
  tags:
    - Update apt packages

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - Update apt packages

- name: Installing dependencies
  become: true
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
  tags:
    - installing dependencies

- name: Confirming docker installation
  become: true
  shell: docker run hello-world
  register: dockercheck

- name: Confirming docker installation
  debug:
    var: dockercheck.stdout


